# generated by datamodel-codegen:
#   filename:  amplifyconfiguration.json
#   timestamp: 2023-04-18T02:51:01+00:00
# Note: Has since been updated since the auth generation. This file was autogenerated from an example json file.
# If I ever find an official schema to the configuration this model would be much more accurate.

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel


class IdentityManager(BaseModel):
    Default: Dict[str, Any]


class CognitoIdentityDefault(BaseModel):
    PoolId: str
    Region: str


class CognitoIdentity(BaseModel):
    Default: CognitoIdentityDefault


class CredentialsProvider(BaseModel):
    CognitoIdentity: CognitoIdentity


class CognitoUserPoolDefault(BaseModel):
    PoolId: str
    AppClientId: str
    Region: str


class CognitoUserPool(BaseModel):
    Default: CognitoUserPoolDefault


class OAuth(BaseModel):
    WebDomain: str
    AppClientId: str
    SignInRedirectURI: str
    SignOutRedirectURI: str
    Scopes: List[str]


class PasswordProtectionSettings(BaseModel):
    passwordPolicyMinLength: int
    passwordPolicyCharacters: List


class AuthDefault(BaseModel):
    OAuth: OAuth
    authenticationFlowType: str
    socialProviders: List
    usernameAttributes: List
    signupAttributes: List[str]
    passwordProtectionSettings: PasswordProtectionSettings
    mfaConfiguration: str
    mfaTypes: List[str]
    verificationMechanisms: List[str]


class AuthClass(BaseModel):
    Default: AuthDefault


class AwsCognitoAuthPlugin(BaseModel):
    UserAgent: str
    Version: str
    IdentityManager: IdentityManager
    CredentialsProvider: CredentialsProvider
    CognitoUserPool: CognitoUserPool
    Auth: AuthClass


class Plugins(BaseModel):
    awsCognitoAuthPlugin: AwsCognitoAuthPlugin


class Auth(BaseModel):
    plugins: Plugins


class AmplifyConfiguration(BaseModel):
    UserAgent: str
    Version: str
    auth: Auth